#!/usr/bin/env sh

# If `./profile` hasn't been run, run it here
if [ -z "${df_profile_initialized}" ]; then
    . "${DOTFILES_DIR}/shell/profile"
fi

for df_autostart_file in "${DOTFILES_DIR}"/shell/autostart.d/*; do
    if
        [ -e "${df_autostart_file}" ] &&
        [ "${df_autostart_file%"/.gitignore"}" = "${df_autostart_file}" ] &&
        [ "${df_autostart_file%".disabled"}" = "${df_autostart_file}" ]
    then
        . "${df_autostart_file}"
    fi
done

unset df_autostart_file
unset df_profile_initialized

