#!/usr/bin/env sh

# If `./profile` hasn't been run, run it here
if [ -z "${df_profile_initialized}" ]; then
    . "${DOTFILES_DIR}/shell/profile"
fi

for df_interactive_file in "${DOTFILES_DIR}"/shell/interactive.d/*; do
    if
        [ -e "${df_interactive_file}" ] &&
        [ "${df_interactive_file%"/.gitignore"}" = "${df_interactive_file}" ] &&
        [ "${df_interactive_file%".disabled"}" = "${df_interactive_file}" ]
    then
        . "${df_interactive_file}"
    fi
done

unset df_interactive_file

