#!/usr/bin/env sh

# Create needed functions

df_command_exists() (
    if alias "$1" >/dev/null 2>&1; then
        unalias "$1" >/dev/null 2>&1
    fi

    command -v "$1" >/dev/null 2>&1
)

df_safe_source() {
    if [ -f "$1" ]; then
        . "$1"
    fi
}

# Start sourcing

for df_profile_file in "${DOTFILES_DIR}"/shell/profile.d/*; do
    if
        [ -e "${df_profile_file}" ] &&
        [ "${df_profile_file%"/.gitignore"}" = "${df_profile_file}" ] &&
        [ "${df_profile_file%".disabled"}" = "${df_profile_file}" ]
    then
        . "${df_profile_file}"
    fi
done
unset df_profile_file

# Let `./interactive` know that we've already initialized
export df_profile_initialized="true"

unset -f df_safe_source
