#!/usr/bin/env bash

set -e

if [ ! -d "${HOME}/.asdf" ]; then
    git clone https://github.com/asdf-vm/asdf.git "${HOME}/.asdf" --branch v0.10.0
    . "${HOME}/.asdf/asdf.sh"
    asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
else
    echo "Directory \"${HOME}/.asdf\" already exists, aborting"
    exit 1
fi
