#!/usr/bin/env sh

if command -v flatpak >/dev/null 2>&1; then

    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    flatpak install flathub \
        org.freedesktop.Platform.ffmpeg-full \
        com.discordapp.Discord \
        com.spotify.Client

else

    echo "Flatpak doesn't seem to be installed. Exiting..."

fi
