#!/usr/bin/env sh

# Install Visual Studio Code plugins

if command -v code >/dev/null 2>&1; then

    code \
        --install-extension "bmewburn.vscode-intelephense-client" \
        --install-extension "christian-kohler.path-intellisense" \
        --install-extension "dbaeumer.vscode-eslint" \
        --install-extension "catppuccin.catppuccin-vsc" \
        --install-extension "editorconfig.editorconfig" \
        --install-extension "esbenp.prettier-vscode" \
        --install-extension "junstyle.php-cs-fixer" \
        --install-extension "golang.Go" \
        --install-extension "naumovs.color-highlight" \
        --install-extension "neilbrayfield.php-docblocker" \
        --install-extension "timonwong.shellcheck" \
        --install-extension "vscode-icons-team.vscode-icons" \
        --install-extension "whatwedo.twig" \
        --install-extension "rust-lang.rust-analyzer" \
        --install-extension "ms-vscode-remote.remote-ssh"

else

    echo "Visual Studio Code doesn't seem to be installed. Exiting..."

fi
