#!/usr/bin/env sh

# Gnome Settings

if command -v gsettings >/dev/null 2>&1; then

    # Workspace Settings
    gsettings set org.gnome.shell.overrides workspaces-only-on-primary false

    # Night light settings
    gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
    gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-automatic true
    gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-from 20
    gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-to 8
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 2700

    # Keyboard Settings
    gsettings set org.gnome.desktop.peripherals.keyboard repeat true
    gsettings set org.gnome.desktop.peripherals.keyboard delay 250
    gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 20

    # Use 12-hour clock
    gsettings set org.gnome.desktop.interface clock-format '12h'

    # Show Battery Percentage
    gsettings set org.gnome.desktop.interface show-battery-percentage true

    # Disable Autorun
    gsettings set org.gnome.desktop.media-handling autorun-never true

    # Disable error reporting and usage stats
    gsettings set org.gnome.desktop.privacy send-software-usage-stats false
    gsettings set org.gnome.desktop.privacy report-technical-problems false

    # Disable recently used files in nautilus
    gsettings set org.gnome.desktop.privacy remember-recent-files false
    gsettings set org.gnome.desktop.privacy recent-files-max-age 3

    # Add minimize and maximize buttons to windows
    gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"

    # Enable resizing of windows using Super+Right Mouse Click and dragging
    gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true

    # Other settings
    gsettings set org.gnome.desktop.privacy remove-old-temp-files true
    gsettings set org.gnome.desktop.privacy remove-old-trash-files true
    gsettings set org.gnome.desktop.session idle-delay 900

    # Gedit settings
    gsettings set org.gnome.gedit.preferences.editor display-right-margin true
    gsettings set org.gnome.gedit.preferences.editor right-margin-position 80
    gsettings set org.gnome.gedit.preferences.editor scheme 'solarized-dark'
    gsettings set org.gnome.gedit.preferences.editor highlight-current-line true
    gsettings set org.gnome.gedit.preferences.editor bracket-matching true
    gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
    gsettings set org.gnome.gedit.preferences.editor insert-spaces true
    gsettings set org.gnome.gedit.preferences.editor tabs-size 4
    gsettings set org.gnome.gedit.preferences.editor auto-indent true

fi

