" Disable Vi compatibility mode
set nocompatible

set encoding=utf-8

" Set vim config location
let vim_dir = expand('~/.vim')

" Set vim plugins location
if empty($XDG_DATA_HOME)
    let plugins_dir = expand('~/.local/share/vim/plugged')
else
    let plugins_dir = $XDG_DATA_HOME . '/vim/plugged'
endif

" Per-system file for settings that need to occur before all other settings {{{
runtime before.vim
" }}}

" Plugin configuration Before {{{
runtime config/plugin-ale.vim
" }}}

" Primary Configuration {{{
runtime config/functions.vim
runtime config/base.vim
runtime config/plugins.vim
runtime config/autocmds.vim
runtime config/mappings.vim
runtime config/commands.vim
runtime config/files.vim
runtime config/buffers.vim
runtime config/folding.vim
runtime config/indentation.vim
runtime config/searching.vim
runtime config/statusline.vim
runtime config/colors.vim
" }}}

" Plugin configuration After {{{
runtime config/plugin-airline.vim
runtime config/plugin-markdown.vim
runtime config/plugin-editorconfig.vim
" }}}

" Per-system file for settings that need to occur after all other settings {{{
runtime after.vim
" }}}

