#!/usr/bin/env sh

# Allow aliases in sudo commands
alias sudo="sudo "

alias mvim="mvim --remote-silent"

if command_exists vim; then
    alias vi="vim"
    alias e="vim"
fi

alias grep="grep --color=auto"
alias df="df -h"
# I usually only use du to get the total space used by a directory
alias du="du -hcs"
