#!/usr/bin/env sh

if command_exists brew; then
    export ARCHFLAGS=${ARCHFLAGS:-"-arch x86_64"}
fi

if command_exists vim; then
    export EDITOR="vim"
    export VISUAL="vim"
fi

# Setup the golang path if it isn't already set
export GOPATH=${GOPATH:-"$HOME/Projects/go"}

# Setup defaults for XDG
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME/.config"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-"$HOME/.cache"}
export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-"$HOME/.run"}
export XDG_DATA_HOME=${XDG_DATA_HOME:-"$HOME/.local/share"}

export HOMEBREW_NO_ANALYTICS=1

export PAGER=${PAGER:-"less"}
export LESS=${LESS:-"-CRi -x4"}

# Enable color in some commands on OSX and some BSDs
export CLICOLOR=1
