#!/usr/bin/env sh

command_exists "brew" && export ARCHFLAGS="-arch x86_64"

if command_exists vim; then
    export EDITOR="vim"
    export VISUAL="vim"
fi

# This allows some prompt themes to hide the username and hostname
# when you aren't logged into a remote machine
[ -z "${SSH_CLIENT:-}" ] && export DEFAULT_USER="anthony"

# Setup the golang path if it isn't already set
: "${GOPATH:="$HOME/Projects/go"}"

# Setup defaults for XDG
: "${XDG_CONFIG_HOME:="$HOME/.config"}"
: "${XDG_CACHE_HOME:="$HOME/.cache"}"
: "${XDG_RUNTIME_DIR:="$HOME/.run"}"
: "${XDG_DATA_HOME:="$HOME/.local/share"}"

export HOMEBREW_NO_ANALYTICS=1
