#!/usr/bin/env sh

if command_exists tmux; then
  # Don't auto-start by default
  : "${TMUX_AUTOSTART:=false}"
  : "${TMUX_AUTOSTART_SESSION_NAME:=df_autostart_session}"

  if [ -z "$TMUX" ] && [ "$TMUX_AUTOSTART" = "true" ]; then
    # Using new-session with the -A flag requires tmux >=1.8
    \tmux new-session -A -s "$TMUX_AUTOSTART_SESSION_NAME"
  fi
fi
